# Generated by Django 3.2.9 on 2021-11-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_key', models.IntegerField(blank=True, null=True)),
                ('field_key', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_type_id', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capital_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_key', models.CharField(blank=True, max_length=10, null=True)),
                ('crop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarmYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_key', models.CharField(blank=True, max_length=10, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'farm_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, max_length=10, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_state', models.CharField(blank=True, max_length=2, null=True)),
                ('field_county', models.CharField(blank=True, max_length=255, null=True)),
                ('date_purchased', models.DateTimeField(blank=True, null=True)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('crop_acreage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pasture_acreage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('crp_acreage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, max_length=10, null=True)),
                ('year_key', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'field_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldYearCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, max_length=10, null=True)),
                ('year_key', models.IntegerField(blank=True, null=True)),
                ('crop_key', models.CharField(blank=True, max_length=10, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'field_year_crop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldYearTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, max_length=10, null=True)),
                ('year_key', models.IntegerField(blank=True, null=True)),
                ('trans_type', models.CharField(blank=True, max_length=10, null=True)),
                ('object_type', models.CharField(blank=True, max_length=25, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_category', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'field_year_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_key', models.CharField(blank=True, max_length=10, null=True)),
                ('field_key', models.CharField(blank=True, max_length=10, null=True)),
                ('initial_year', models.IntegerField(blank=True, null=True)),
                ('bank_id', models.CharField(blank=True, max_length=10, null=True)),
                ('loan_type_id', models.CharField(blank=True, max_length=10, null=True)),
                ('initial_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_terms', models.FloatField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('amort_years', models.IntegerField(blank=True, null=True)),
                ('term_years', models.IntegerField(blank=True, null=True)),
                ('date_of_initiation', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_key', models.CharField(blank=True, max_length=10, null=True)),
                ('year_key', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('principal_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StagingFieldYearCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, max_length=10, null=True)),
                ('year_key', models.IntegerField(blank=True, null=True)),
                ('crop_key', models.CharField(blank=True, max_length=10, null=True)),
                ('pushed', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staging_field_year_crop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StagingFieldYearTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, max_length=10, null=True)),
                ('year_key', models.IntegerField(blank=True, null=True)),
                ('trans_type', models.CharField(blank=True, max_length=10, null=True)),
                ('object_type', models.CharField(blank=True, max_length=25, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_category', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pushed', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staging_field_year_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StagingLegitTransactionObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(blank=True, max_length=25, null=True, unique=True)),
            ],
            options={
                'db_table': 'staging_legit_transaction_objects',
                'managed': False,
            },
        ),
    ]
