"""
Django settings for farm project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

DB = os.getenv('DB')
DBUSER = os.getenv('DBUSER')
DBPW = os.getenv('DBPW')
# Database configuration – use MySQL if environment variables are set, otherwise fall back to a local SQLite file.
# (The actual DATABASES dict is defined later after BASE_DIR is set.)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ADMIN_SITE_HEADER = "Farm DB Accounting"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1234567890abcdefghijklmnopqrstuvwx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.{}.{}'.format(i,j) for i in range(256) for j in range(256)]
ALLOWED_HOSTS += ['127.0.0.1']
ALLOWED_HOSTS += ['host.docker.internal']
ALLOWED_HOSTS += ['localhost']
ALLOWED_HOSTS += ['0.0.0.0']
ALLOWED_HOSTS += ['farm-db', 'web', 'web:8000']
# Application definition

INSTALLED_APPS = [
    'farms.apps.FarmsConfig',    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tables2',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

# ---------------------------------------------------------------------
# REST framework configuration – increase default page size to avoid 504s when the
# React client requests ``/api/transactions/`` without pagination parameters.
# The frontend can still request a specific page or set ``page_size`` in the
# query string if it wants fewer records.
# ---------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # A generous default; adjust as needed for production loads.
    "PAGE_SIZE": 500,
    # Use token authentication by default for API endpoints.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
}

# ------------------------------------------------------------
# First‑principles configuration: we manage the database schema
# manually with the SQL script mounted at /docker-entrypoint-initdb.d.
# Disable Django's migration system for all built‑in apps and our own
# ``farms`` app so that the ORM works against the existing tables
# without attempting to run migrations on container start.
# Setting a module path to ``None`` tells Django that the app has no
# migrations. This is safe because the schema is created externally.
# ------------------------------------------------------------
# Disable migrations for built‑in Django apps only. Keeping ``farms`` enabled
# allows us to apply the migration files that define the required tables (e.g.
# ``field_year_transaction``). This ensures the MySQL database is correctly
# populated when running ``manage.py migrate``.
MIGRATION_MODULES = {
    'admin': None,
    'auth': None,
    'contenttypes': None,
    'sessions': None,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farm.urls'

SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/var/www/farm_app/farm/farms/templates/',
                  '/var/www/farm_app/farm/farms/templates/farms', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'farm.wsgi.application'


# Use MySQL in production (Docker). When running locally without the Docker
# environment variables, fall back to the defaults defined in ``docker-compose.yml``.
if not DB:
    DB = 'farmdb'
if not DBUSER:
    DBUSER = 'farm_user'
if not DBPW:
    DBPW = 'farm_password'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB,
        'USER': DBUSER,
        'PASSWORD': DBPW,
        # Default to Docker service name 'db' so Django can connect when running
        # inside the container or during tests without requiring an env var.
        'HOST': os.getenv('DBHOST', 'db'),   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}

# ---------------------------------------------------------------------
# CORS configuration – allow all origins for local development. In a real
# deployment you would restrict this to your frontend domain.
# ---------------------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True

# Configure Django's test database to use a temporary MySQL schema. Django will
# automatically prefix the name with ``test_`` when using MySQL, but we set it
# explicitly for clarity.
# Use the same database for tests to avoid permission errors when Django tries to
# create a ``test_`` prefixed schema. This is acceptable in our development
# environment where the MySQL user has limited privileges.
# Mirror the default database for tests to avoid creating a separate test schema.
DATABASES['default']['TEST'] = {
    'MIRROR': 'default',
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REQUIRED_FOR_CRUD = False
PERMISSION_REQUIRED_FOR_CRUD = False
PROJECT_NAME = 'farm'
