"""
Django settings for farm project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

DB = os.getenv('DB')
DBUSER = os.getenv('DBUSER')
DBPW = os.getenv('DBPW')
# Database configuration – use MySQL if environment variables are set, otherwise fall back to a local SQLite file.
# (The actual DATABASES dict is defined later after BASE_DIR is set.)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ADMIN_SITE_HEADER = "Farm DB Accounting"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1234567890abcdefghijklmnopqrstuvwx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.{}.{}'.format(i,j) for i in range(256) for j in range(256)]
ALLOWED_HOSTS += ['127.0.0.1']
ALLOWED_HOSTS += ['host.docker.internal']
ALLOWED_HOSTS += ['localhost']
ALLOWED_HOSTS += ['0.0.0.0']
ALLOWED_HOSTS += ['farm-db', 'web', 'web:8000']
# Application definition

INSTALLED_APPS = [
    'farms.apps.FarmsConfig',    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tables2',
    'rest_framework',
]

# ------------------------------------------------------------
# First‑principles configuration: we manage the database schema
# manually with the SQL script mounted at /docker-entrypoint-initdb.d.
# Disable Django's migration system for all built‑in apps and our own
# ``farms`` app so that the ORM works against the existing tables
# without attempting to run migrations on container start.
# Setting a module path to ``None`` tells Django that the app has no
# migrations. This is safe because the schema is created externally.
# ------------------------------------------------------------
MIGRATION_MODULES = {
    'admin': None,
    'auth': None,
    'contenttypes': None,
    'sessions': None,
    'farms': None,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farm.urls'

SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/var/www/farm_app/farm/farms/templates/',
                  '/var/www/farm_app/farm/farms/templates/farms', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'farm.wsgi.application'


# Database configuration moved to conditional block below (supports MySQL via env vars or fallback SQLite).
# Database configuration – use MySQL if environment variables are set, otherwise fall back to a local SQLite file.
if DB and DBUSER and DBPW:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB,
            'USER': DBUSER,
            'PASSWORD': DBPW,
            'HOST': os.getenv('DBHOST', 'localhost'),   # Or an IP Address that your DB is hosted on
            'PORT': '3306',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REQUIRED_FOR_CRUD = False
PERMISSION_REQUIRED_FOR_CRUD = False
PROJECT_NAME = 'farm'
